// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type ChildSuggest struct {
	Word   string   `json:"word"`
	Growth *Growth  `json:"growth"`
	Graphs []*Graph `json:"graphs"`
}

type Graph struct {
	Date  string  `json:"date"`
	Value float64 `json:"value"`
}

type Growth struct {
	Short  Arrow `json:"short"`
	Midium Arrow `json:"midium"`
	Long   Arrow `json:"long"`
}

type Suggest struct {
	Word          string          `json:"word"`
	ChildSuggests []*ChildSuggest `json:"childSuggests"`
}

type User struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Arrow string

const (
	ArrowUp   Arrow = "Up"
	ArrowFlat Arrow = "Flat"
	ArrowDown Arrow = "Down"
)

var AllArrow = []Arrow{
	ArrowUp,
	ArrowFlat,
	ArrowDown,
}

func (e Arrow) IsValid() bool {
	switch e {
	case ArrowUp, ArrowFlat, ArrowDown:
		return true
	}
	return false
}

func (e Arrow) String() string {
	return string(e)
}

func (e *Arrow) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Arrow(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Arrow", str)
	}
	return nil
}

func (e Arrow) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
