version: '3'
services:
  gateway:
    build:
      context: ./
      # dockerfile: gateway/Dockerfile #prd
      dockerfile: gateway/docker-local/Dockerfile #local
    container_name: 2929gateway
    ports:
      - "8080:8080"
    environment:
      - "ACCOUNT_ADDR=account:50051" #local
    volumes:
      - ./gateway:/go/src/github.com/originbenntou/2929BE/gateway #local
  account:
    build:
      context: ./
      # dockerfile: account/Dockerfile #prd
      dockerfile: account/docker-local/Dockerfile #local
    container_name: 2929account
    ports:
      - "50051:50051"
    environment:
      - "ENV=LOCAL" #local
    volumes:
      - ./account:/go/src/github.com/originbenntou/2929BE/account #local
  mysql:
    build:
      context: ./
      dockerfile: mysql/Dockerfile
    container_name: 2929mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: account, trend
      MYSQL_USER: 2929
      MYSQL_PASSWORD: 2929
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
