// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Group struct {
	ID string `json:"id"`
}

type Text struct {
	TextID   string `json:"textId"`
	TextData string `json:"textData"`
}

type TextCondition struct {
	TextID string `json:"textId"`
}

type User struct {
	ID     string   `json:"id"`
	Name   string   `json:"name"`
	Groups []*Group `json:"groups"`
}
